-- ============================================================================
-- Phase 5 / Migration 13 - phone OTP storage + admin notification queue
-- ============================================================================
-- Phone OTPs are generated by server actions, stored hashed, and consumed on
-- verification. The plaintext OTP is logged by the server action only during
-- local testing and should be removed when a real SMS provider is connected.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.phone_verification_otps (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  phone_e164    text NOT NULL,
  otp_hash      text NOT NULL,
  attempts      int NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  expires_at    timestamptz NOT NULL,
  consumed_at   timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_phone_otps_user_active
  ON public.phone_verification_otps (user_id, created_at DESC)
  WHERE consumed_at IS NULL;

ALTER TABLE public.phone_verification_otps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS phone_otps_select_own ON public.phone_verification_otps;
CREATE POLICY phone_otps_select_own ON public.phone_verification_otps
  FOR SELECT TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS phone_otps_staff_read ON public.phone_verification_otps;
CREATE POLICY phone_otps_staff_read ON public.phone_verification_otps
  FOR SELECT TO authenticated USING (public.is_staff());

REVOKE INSERT, UPDATE, DELETE ON public.phone_verification_otps FROM anon, authenticated;

-- Queue admin department alerts whenever the order confirmation history row
-- lands. The customer email queue is inserted by the previous notification
-- trigger; these rows are specifically for Kakeez operations.
CREATE OR REPLACE FUNCTION public.enqueue_order_status_notification()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public AS $$
DECLARE
  v_order public.orders%ROWTYPE;
  v_template text;
  v_payload jsonb;
BEGIN
  SELECT * INTO v_order
    FROM public.orders
   WHERE id = NEW.order_id;

  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  v_template := CASE
    WHEN NEW.from_status IS NULL AND NEW.to_status = 'pending_confirmation' THEN 'order_confirmed'
    ELSE 'order_status_' || NEW.to_status
  END;

  v_payload := jsonb_build_object(
    'order_id', v_order.id,
    'order_number', v_order.order_number,
    'status', NEW.to_status,
    'previous_status', NEW.from_status,
    'customer_name', v_order.customer_name,
    'customer_email', v_order.customer_email,
    'customer_phone', v_order.customer_phone,
    'total_minor', v_order.total_minor,
    'currency', v_order.currency,
    'delivery_slot_date', v_order.delivery_slot_date,
    'delivery_slot_window', v_order.delivery_slot_window,
    'reason', NEW.reason
  );

  IF v_order.user_id IS NOT NULL THEN
    INSERT INTO public.notifications (
      order_id, user_id, audience, channel, template_key, payload, status
    ) VALUES (
      v_order.id, v_order.user_id, 'user', 'email', v_template, v_payload, 'queued'
    );
  END IF;

  IF NEW.from_status IS NULL AND NEW.to_status = 'pending_confirmation' THEN
    INSERT INTO public.notifications (
      order_id, user_id, audience, channel, template_key, payload, status
    ) VALUES
      (v_order.id, NULL, 'admin', 'in_app', 'new_order', v_payload, 'queued'),
      (v_order.id, NULL, 'admin', 'email', 'admin_new_order', v_payload, 'queued'),
      (v_order.id, NULL, 'admin', 'wa_template', 'admin_new_order', v_payload, 'queued');
  END IF;

  RETURN NEW;
END $$;
